### ISSUE TITLE
I met a problem about sementic-release but I can't find solution for it..

### ISSUE THREAD

**Issue by manudeli** [bmvantunes/youtube-2021-may-automatic-publish-npm-semantic-release-and-github-actions#2]
@bmvantunes Hello bruno!

I met a problem about sementic-release but I can't find solution for it..

Did you meet this problem too?

- My repo
https://github.com/manudeli/semantic-release-github-actions

if you know solution, Could you help me please?

```
Run yarn semantic-release
yarn run v1.22.18
$ semantic-release --branches master
[[7](https://github.com/manudeli/semantic-release-github-actions/runs/6245258001?check_suite_focus=true#step:5:7):09:43 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[7:09:44 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[7:09:46 AM] [semantic-release] › ✔  Run automated release from branch master on repository ***github.com/manudeli/semantic-release-github-actions.git
[7:09:46 AM] [semantic-release] › ✖  The command "git push --dry-run --no-verify ***github.com/manudeli/semantic-release-github-actions.git HEAD:master" failed with the error message remote: Permission to manudeli/semantic-release-github-actions.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/manudeli/semantic-release-github-actions.git/': The requested URL returned error: 403.
[7:09:46 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[7:09:46 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[7:09:46 AM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[7:09:46 AM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository manudeli/semantic-release-github-actions.

[7:09:46 AM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL ***github.com/manudeli/semantic-release-github-actions.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/work/semantic-release-github-actions/semantic-release-github-actions/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/work/semantic-release-github-actions/semantic-release-github-actions/node_modules/semantic-release/index.js:9[8](https://github.com/manudeli/semantic-release-github-actions/runs/6245258001?check_suite_focus=true#step:5:8):11)
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/manudeli/semantic-release-github-actions/runs/6245258001?check_suite_focus=true#step:5:9)6:5)
    at async module.exports (/home/runner/work/semantic-release-github-actions/semantic-release-github-actions/node_modules/semantic-release/index.js:268:[22](https://github.com/manudeli/semantic-release-github-actions/runs/6245258001?check_suite_focus=true#step:5:22))
    at async module.exports (/home/runner/work/semantic-release-github-actions/semantic-release-github-actions/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `***github.com/manudeli/semantic-release-github-actions.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by bmvantunes** [comment]
You need to give permissions to push to master 🙂

**Comment by manudeli** [comment]
> You need to give permissions to push to master 🙂

<img width="812" alt="image" src="https://user-images.githubusercontent.com/61593290/166154658-412e9c39-c13d-4593-bec2-79ec91f753b9.png">

@bmvantunes bruno, Isn't it right setting for giving semantic-release permissions to push to master? 😂😂😂
I can't find solution to permit yet....

Could you explain any solution more detail please?

**Comment by manudeli** [comment]
I made one more repository to test this setting but I couldn't find any solution...
